name: Build

on:
  workflow_call:
    inputs:
      need_upload_artifact:
        required: true
        type: boolean

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build

      - name: Upload Build Artifact
        if: ${{ inputs.need_upload_artifact }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: build