name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/share/_build.yml
    with:
      need_upload_artifact: true

  deploy:
    needs: build
    uses: ./.github/workflows/share/_deploy.yml