name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      need_upload_artifact: true

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    uses: ./.github/workflows/_deploy.yml