name: Test Build

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  test_build:
    uses: ./.github/workflows/_build.yml
    with:
      need_upload_artifact: false

  actions-timeline:
    needs: [test_build]
    runs-on: ubuntu-latest
    steps:
    - uses: Kesin11/actions-timeline@v2.2.1